-- COMANDOS DE DROP TABLE RESUMIDOS 

DROP TABLE PARTICIPA CASCADE CONSTRAINTS;
DROP TABLE COMPETICAO_EM_EVENTO CASCADE CONSTRAINTS;
DROP TABLE COMPETICAO CASCADE CONSTRAINTS;
DROP TABLE ESPORTES_EVENTO CASCADE CONSTRAINTS;
DROP TABLE EVENTO CASCADE CONSTRAINTS;
DROP TABLE ESPORTES_PRATICADOS CASCADE CONSTRAINTS;
DROP TABLE SESSAO_DE_MENTORIA CASCADE CONSTRAINTS;
DROP TABLE EQUIPAMENTOS_DE_TREINO CASCADE CONSTRAINTS;
DROP TABLE LOCAL_DE_TREINO CASCADE CONSTRAINTS;
DROP TABLE RECORDES_DETIDOS CASCADE CONSTRAINTS;
DROP TABLE RECORDES CASCADE CONSTRAINTS;
DROP TABLE OBJETIVO_DE_DESENVOLVIMENTO CASCADE CONSTRAINTS;
DROP TABLE DOENCAS_MENTOR CASCADE CONSTRAINTS;
DROP TABLE DOENCAS_ATLETA CASCADE CONSTRAINTS;
DROP TABLE ALERGIAS_MENTOR CASCADE CONSTRAINTS;
DROP TABLE ALERGIAS_ATLETA CASCADE CONSTRAINTS;
DROP TABLE ATLETA CASCADE CONSTRAINTS;
DROP TABLE MENTOR CASCADE CONSTRAINTS;
DROP TABLE PESSOA CASCADE CONSTRAINTS;
